import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Blog - Lucas Fernando',
  description: 'Generated by create next app',
  icons: "/logo.svg"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  )
}
